### PR TITLE
Add basic e2e test

### PR DESCRIPTION
**Pull request by dtuite**
Running nightwatch tests requires that the latest selenium webdriver JAR
be present at `:project_root:/bin/selenium-server-standaline.jar`. See the
nightwatch [Getting started](http://nightwatchjs.org/guide#installation) page for more information.

Use `npm run e2e` to run the end to end tests.

### CODE REVIEW

**Comment by dtuite** [comment]
I'd like to write a bunch more of these because I find I can't adequately write more than low level unit tests with `React.addons.TestUtils.Simulate`. I think it's important that the behaviour of the component is tested in context.

Let me know what you think.

**Comment by bmcmahen** [comment]
cool -- unfamiliar with this. will take a look though, thanks.

**Comment by dtuite** [comment]
All it does so far is type into your example page and assert that the number of chars remaining is decreasing as expected. I can write more comprehensive tests for other functionality.

Let me know if you have any questions.

**Comment by bmcmahen** [comment]
This looks great. Thanks.

**Comment by dtuite** [comment]
Cool. If things go to plan I'll have tests for other functionality coming soon.

**Pull request merged**
